# Generated by Django 5.2.3 on 2025-08-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='Menu',
        ),
    ]
