# Generated by Django 5.2.3 on 2025-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
